import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";

export const translations = JSON.parse(readFileSync(new URL("../../data/localization.json", import.meta.url), "utf8"));
export const localizationSource = `// Generated by scripts/build-site.mjs from data/localization.json.\nwindow.PARADIGM_TRANSLATIONS = ${JSON.stringify(translations, null, 2)};\n`;
export const localizationVersion = createHash("sha256").update(localizationSource).digest("hex").slice(0, 12);
const escape = (value) => String(value).replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
export const formatCopy = (text, params = {}) => text.replace(/\{(\w+)\}/g, (match, key) => params[key] ?? match);
export function copyAttributes(text, attribute = "text", params = {}) {
  if (!Object.hasOwn(translations, text)) return "";
  const suffix = attribute === "text" ? "" : `-${attribute}`;
  return ` data-l10n${suffix}="${escape(text)}"${Object.keys(params).length ? ` data-l10n-params="${escape(JSON.stringify(params))}"` : ""}`;
}

const dimensionLabels = { 肩寬: "Shoulder W", 胸寬: "Chest W", 袖長: "Sleeve L", 衣長: "Body L", 褲頭寬: "Waist W", 褲腳寬: "Leg W", 內側長: "Inseam L", 外側長: "Outseam L" };
export function dimensionCopy(label) { return dimensionLabels[label] || label; }
export function recommendationCopy(text) {
  const match = text.match(/^建議(身高|腰圍)(\s*)([<>]\s*\d+|\d+~\d+)(\s*)著用 (M|L|XL)(.*)$/u);
  if (!match) return null;
  const key = match[1] === "身高" ? "For Height {range}, Size {size}" : "For Waist {range}, Size {size}";
  const params = { range: match[3], size: match[5] };
  return { key, params, text: formatCopy(key, params) + match[6], original: text };
}
