import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";

export const FX_SOURCE = "https://cpx.cbc.gov.tw/api/OpenData/FTDOpenData_Month";
export const FX_METHOD = "Geometric average of business-day interbank closing rates";
export function validateReference(reference) {
  assert.match(reference.month, /^\d{4}-(?:0[1-9]|1[0-2])$/, "Invalid reference month");
  assert.ok(typeof reference.twdPerUsd === "number" && Number.isFinite(reference.twdPerUsd) && reference.twdPerUsd > 0, "Invalid TWD per USD rate");
  assert.equal(reference.source, FX_SOURCE, "Reference must use the official monthly average source");
  assert.equal(reference.method, FX_METHOD, "Reference must describe the official averaging method");
  return reference;
}

export const storefronts = JSON.parse(readFileSync(new URL("../../data/storefronts.json", import.meta.url), "utf8"));
export const reference = validateReference(JSON.parse(readFileSync(new URL("../../data/pricing-reference.json", import.meta.url), "utf8")));
assert.ok(storefronts.options.some((option) => option.value === storefronts.defaultValue), "Invalid default storefront");
assert.equal(new Set(storefronts.options.map((option) => option.value)).size, storefronts.options.length, "Duplicate storefront");
for (const option of storefronts.options) {
  const market = storefronts.markets[option.market];
  assert.ok(market && ["TWD", "USD"].includes(market.currency), "Invalid storefront market");
  assert.equal(option.detail, market.currency, "Selector currency must agree with its market");
  assert.ok(["en", "zh-Hant"].includes(option.language), "Invalid storefront language");
}
export const pricingConfigSource = `// Generated by scripts/build-site.mjs from data/storefronts.json and data/pricing-reference.json.\nwindow.PARADIGM_PRICING_CONFIG = ${JSON.stringify({ storefronts, reference }, null, 2)};\n`;
export const pricingConfigVersion = createHash("sha256").update(pricingConfigSource).digest("hex").slice(0, 12);
